### ISSUE TITLE
Audio In Select

### ISSUE THREAD

**Issue by TheBiggestBread** [aza547/wow-recorder#103]
I use Nvidia broadcast for discord, but the program will record through my mic, and all i can hear is my clicking

**Comment by tdaugaard** [comment]
This has already been fixed in `main` branch, but hasn't been released yet. The fix is, that you can select which input and output devices to include in the recordings.

Is that what you're looking for?

**Comment by aza547** [comment]
I suspect so, so closing. Please re-open if you disagree.
