### ISSUE TITLE
Feature: push to talk for mic recording

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#125]
Title

**Comment by TKardinal** [comment]
Seconded.

**Comment by aza547** [comment]
Electron has a hard time detecting a key-up event when the app isn't focused. In-fact it's just not possible. See here:
https://github.com/electron/electron/issues/7802

**Comment by aza547** [comment]
Despite that looks like streamlabs have already solved this:
https://github.com/stream-labs/desktop/blob/master/app/services/hotkeys.ts

Expect we can crib off that.

**Comment by aza547** [comment]
Done the work for this, just needs some testing.

**Comment by aza547** [comment]
It's merged to main and I'm somewhat confident it's good. Need some more time to soak before the release but closing this.
