### ISSUE TITLE
Spontaneously and quietly we stop asserting OBS signalling 

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#139]
![image](https://user-images.githubusercontent.com/32389325/191578769-b671fcb0-dcef-43d0-980f-0ce6fb4e4d68.png)
[WarcraftRecorder (1).log](https://github.com/aza547/wow-recorder/files/9619253/WarcraftRecorder.1.log)

**Comment by Emme** [comment]
The OSN log:
[2022-09-20 19-44-54.txt](https://github.com/aza547/wow-recorder/files/9619292/2022-09-20.19-44-54.txt)

**Comment by aza547** [comment]
This is interesting:

```
[000:03:17:45.323.033.200][12688][Warning] [AMF] <Id: 11> No output Packet, encoder is overloaded!
```

Annoyingly I think the OSN timestamps are from start-up time, we can probably cross reference to see if it matches up.

**Comment by aza547** [comment]
I think we handle the AMF encoder pretty badly actually, this might be a product of that. 

See obsRecorder.ts:

```
  if (selectedEncoder.toLowerCase().includes("amf")) {
    // For AMF encoders, can't set 'lossless' bitrate.
    // It interprets it as zero and fails to start.
    // See https://github.com/aza547/wow-recorder/issues/40.
    setSetting('Output', 'Recbitrate', 50000);
  }
```

**Comment by aza547** [comment]
and #40 as per the comment

**Comment by aza547** [comment]
Looks like an interesting read https://obsproject.com/forum/threads/recent-encoding-overloaded-error-with-amf-no-output-packet.124033/

**Comment by aza547** [comment]
Maybe not on second thoughts as I think this was not over a long recording but between a buffer restart. Will come back to this.

**Comment by tdaugaard** [comment]
Would it make sense to expose the available encoders in the Settings window to allow people to pick in case one isn't optimal?

**Comment by aza547** [comment]
It's an interesting question - I don't know is the answer! 

On one hand, if things go wrong it would be great to say "try the other encoder" - on the other hand, it's probably confusing to most users. 

I think I want to expose this, but when I revamp the settings page and include an "advanced tab" or something.

**Comment by aza547** [comment]
Also I think 99% of the time people should use the encoder that allows them to hardware encode. I think we always do that (by hook or by crook) just now by selecting the final encoder of the list. That's something inherited from the OSN example repo. It doesn't really make sense to me why the order is fixed like this, but I've never seen us use a non-nvenc / AMF encoder. I think both of those are hardware encoding for nvidia/AMD respectively.

**Comment by aza547** [comment]
Anyway seems like the AMF encoder might need some attention here. I think we need to have a fiddle with the config. There is a repo for this encoder handling in OBS I think, it's in an issue somewhere (#40). TBC when I'll have time to do that.

**Comment by aza547** [comment]
https://github.com/obsproject/obs-amd-encoder/wiki/Configuration#target-bitrate-peak-bitrate

**Comment by aza547** [comment]
Hit this while testing myself. Nvidia encoder. 

[WarcraftRecorder-2022-09-22.log](https://github.com/aza547/wow-recorder/files/9629078/WarcraftRecorder-2022-09-22.log)
[2022-09-22 20-23-22.txt](https://github.com/aza547/wow-recorder/files/9629079/2022-09-22.20-23-22.txt)
[2022-09-22 20-18-54.txt](https://github.com/aza547/wow-recorder/files/9629080/2022-09-22.20-18-54.txt)

Seemed to stop doing the right thing soon after 20:40. Last successful recording was a raid test.

**Comment by aza547** [comment]
Oh interesting. I think I saw this in early development and never really understood why it happens but the fix seemed to be to ensure we delay some time between stopping and starting.

I think either we were never doing this properly, or have regressed it.

Note the timestamps here, from the final assert:

```
[2022-09-22 20:40:46.248] [info]  [OBS] obsRecorder: stop
[2022-09-22 20:40:46.295] [debug] [OBS] Asserted OBS signal: recording stopping
[2022-09-22 20:40:46.525] [debug] [OBS] Asserted OBS signal: recording stop
[2022-09-22 20:40:46.572] [debug] [OBS] Asserted OBS signal: recording wrote
[2022-09-22 20:40:46.573] [info]  [36m[Recorder] Start recording buffer[39m
[2022-09-22 20:40:46.574] [info]  [OBS] obsRecorder: start
```

and in the log from the initial issue creation:
```
[2022-09-20 23:01:47.404] [debug] [OBS] Asserted OBS signal: recording wrote
[2022-09-20 23:01:47.405] [info]  [Util] Deleting: E:/WoW Recordings/.temp/2022-09-20 22-50-32.mp4
[2022-09-20 23:01:49.409] [info]  [OBS] obsRecorder: start
```

Looks like we do atleast wait for the signal to return, but no more. So, timing condition I reckon, where previously runSizeMonitor() was killing some time for us and avoiding this. 

In recorder.restartBuffrer():
```
  setTimeout(() => {
      obsRecorder.start();
  }, 2000);
```

...but in recorder.finalizeVideo() we do the same thing without the sleep. Admittedly there is lots of code between it but that also includes runSizeMonitor (which was previously blocking - so maybe making this async is the source of the bug).

I think this goes away if we add a forced delay to `recorder.stop()`. Not entirely satisfied with that (adding sleeps to code sucks), but I think that's the right thing to do while we try understand OSN/OBS better.

**Comment by aza547** [comment]
We also call `finalizeVideo()` between the stop and start, which is a no-op if it's a short raid. That's the test type that has caused it in my case I think. I should add some better logging so that is obvious what's happening. 

Not sure this totally lines up with Emme's report though. There was happily 2 seconds between the stop start there. I wonder if something could be hardware dependant here -- i.e. if OBS "recover" in that 2s window then we hit this. 

That's not very convincing, ideally there would be some API call in NodeOBS that was blocking for this. 

Anyway, fixes:
- Raid reset handling should delay start of recording.
- Raid reset should log so it's clear that we're not cutting log.
- Lets bump the window we don't record to 5 seconds. That will avoid the hardware theory. There is virtually no way we don't have a 5 second break between interesting events, and if we do, we'll just miss the start of it, which I can live with.

**Comment by aza547** [comment]
Closing this as hopefully the fixes will sort in next release. Will re-open if not.
