### ISSUE TITLE
Swapping monitors doesn't get new resolution.

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#141]
Tmb hit a bug that when he swapped monitors it managed to hang onto the old resolution.

Was fixed by restarting the app. 

Probably doing something weird with config.

**Comment by aza547** [comment]
Low urgency as easy workaround.

**Comment by aza547** [comment]
[WarcraftRecorder-2022-09-19 (12).log](https://github.com/aza547/wow-recorder/files/9619549/WarcraftRecorder-2022-09-19.12.log)

**Comment by aza547** [comment]
Doesn't occur when running in debug mode, suspect some timing issue

**Comment by tdaugaard** [comment]
Won't be relevant with Game Capture enabled.

**Comment by aza547** [comment]
This is going to be fixed in 3.3.0.
