### ISSUE TITLE
Handle russian characters

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#163]
Pretty sure @tdaugaard had a UTF8 fix for this?

**Comment by aza547** [comment]
https://github.com/aza547/wow-recorder/pull/116

But I'm sure I've seen Russian characters look bad. I'll try get a repro.

**Comment by tdaugaard** [comment]
From my log file:

![image](https://user-images.githubusercontent.com/875107/192387404-fe5340da-8d2e-4f1b-a1cc-d56ca63b9fca.png)

VSCode terminal:

```
 "playerDeaths": [
  {
    "name": "Партосец-Ревущийфьорд",
    "specId": 260,
    "timestamp": 446.67
  }
],
```
![image](https://user-images.githubusercontent.com/875107/192387610-48e65012-cfaa-4eb0-a7a0-39e7d8a4f49f.png)

Video metadata:

![image](https://user-images.githubusercontent.com/875107/192387778-811823e4-cb35-4564-996c-87db06607ebc.png)

**Comment by tdaugaard** [comment]
I'm using "Windows Terminal" - tabbed Terminal that can deal with multiple different shells; much better and no problems with Unicode/ANSI etc.

**Comment by aza547** [comment]
No idea why I'm using naked powershell to be honest. I should start using windows terminal too. But also reproduced that there. 

![image](https://user-images.githubusercontent.com/32389325/192589784-84049bdf-6d0c-4c75-8a61-b19de2057f7c.png)

**Comment by tdaugaard** [comment]
It's an issue with your terminal, not the logs. Perhaps the font you're using? I'm using _CaskaydiaCove NF_.

**Comment by aza547** [comment]
Yeah you're right. Logs show it fine in VSCode. Closing.
