### ISSUE TITLE
Remaining actions after settings revamp

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#164]
Out of time to make finishing touches on settings page and want to release so people can test fixes.  Copying notes from the PR. 

TODO

- Attempt to centralise modifyConfig methods in frontend code.
- Attempt to fix remaining typescript errors in frontend code.
- Any final clean-up we can do / move things to final locations.
- Investigate errors like Error occurred in handler for 'getVideoState': Error: ENOENT: no such file or directory, stat 'D:\wow-recorder-files\2022-09-19 12-28-17.mp4. I think this is happening when the sizemonitor and clean-up after a recording overlap.

**Comment by aza547** [comment]
[tdaugaard](https://github.com/tdaugaard) [22 hours ago](https://github.com/aza547/wow-recorder/pull/161#discussion_r979463372)
I'm thinking we make this an array like recordCategories which just has the labels like "2v2", "Mythic+" but it's not super important.

**Comment by aza547** [comment]
Also can we expose the schema help text in the UI, save people getting config wrong

**Comment by aza547** [comment]
"Make content type config actually do something." 
This was a bit hacky but I'm not totally sure how to do what I want with the types.
Hoping you can educate me tdaugaard.
Talking about the arena bit here where I had to make a mapping.

See categoryRecordConfigMapping for this one.

**Comment by aza547** [comment]
Double setting of cfg params in logs:
```
20:57:31.213 > [Config Service] Set in config store: selectedCategory 6
20:57:31.218 > [Config Service] Set in config store: selectedCategory 6
20:57:37.912 > [Config Service] Set in config store: selectedCategory 5
20:57:37.915 > [Config Service] Set in config store: selectedCategory 5
20:57:39.656 > [Config Service] Set in config store: selectedCategory 6
20:57:39.660 > [Config Service] Set in config store: selectedCategory 6
```

**Comment by tdaugaard** [comment]
> Investigate errors like Error occurred in handler for 'getVideoState': Error: ENOENT: no such file or directory, stat 'D:\wow-recorder-files\2022-09-19 12-28-17.mp4. I think this is happening when the sizemonitor and clean-up after a recording overlap.

I think this may have been remedied by changing to use `getObsLastRecording()`?

**Comment by aza547** [comment]
I think we're done here?
