### ISSUE TITLE
M+ leaver runs need better handling

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#168]
Two fixes in mind:
- Log inactivity timeout (@tdaugaard has written this and it's coming in 2.8.0)
- Zone change when going to a non dungeon zone, see nnoggie's list of zones in MDT code. [Link](https://github.com/Nnoggie/MythicDungeonTools/blob/bf3bd4b83c77df7425473927983ab7342982e720/MythicDungeonTools.lua#L2613)

**Comment by tdaugaard** [comment]
> Zone change when going to a non dungeon zone

Yeah, but that should trigger to _set_ a timeout as well as log inactivity. Could really be baked into the existing callback attached to the  `DataTimeout` event from `CombatLogParser`.

A zone change itself isn't a problem alone.

**Comment by aza547** [comment]
> Yeah, but that should trigger to set a timeout as well as log inactivity. Could really be baked into the existing callback attached to the DataTimeout event from CombatLogParser.

Not sure I'm with you here.

**Comment by aza547** [comment]
Thinking about this a bit more, maybe it's actually OK. If user has SCL, it will stop recording when they exist the config type, so any ZONE_CHANGE out of a dungeon will hit this. Maybe SCL should be the one true method for logging. 

An afk inside a dungeon will stop if there is no logs, but I suspect there will be periodic combat logs for even afk players. Passive buffs applied etc? I'm not sure you actually need to be in combat to write a combat log, but that sounds counter-intuitive.

**Comment by aza547** [comment]
> An afk inside a dungeon will stop if there is no logs, but I suspect there will be periodic combat logs for even afk players. Passive buffs applied etc? I'm not sure you actually need to be in combat to write a combat log, but that sounds counter-intuitive.

Maybe we can be more aggressive and ensure the player is doing something in those logs.

**Comment by tdaugaard** [comment]
> An afk inside a dungeon will stop if there is no logs, but I suspect there will be periodic combat logs for even afk players. Passive buffs applied etc? 

We could apply the `DataTimeout` to only count combat events like damage and such as data?

> Maybe SCL should be the one true method for logging.

I'd be a mistake to lock yourself in on that; I don't think it's an issue, but most people don't want too many add-ons already and if they have either R.IO or MRT, I'm not sure you'll convince them to install SCL, but who knows :D

**Comment by aza547** [comment]
> We could apply the DataTimeout to only count combat events like damage and such as data?

Yeah definitely - but what if there are mobs that are fighting and also populating it - that's why I think we need to be specific to player combat actions.

**Comment by tdaugaard** [comment]
> Yeah definitely - but what if there are mobs that are fighting and also populating it - that's why I think we need to be specific to player combat actions.

I don't _think_ they trigger log events if you're not in combat with them, but I'm not _entirely_ sure and I don't know how to test it. Maybe Junkyard for Mythic+ as it has random mobs spinning around and such.

**Comment by tdaugaard** [comment]
I've had a few abandonen M+ dungeons lately and have had no problems. The only issue I've seen is that it doesn't save the player character for the abandoned keys. I'll work on fixing that.

![image](https://user-images.githubusercontent.com/875107/196006341-e9bc7c86-81a9-41b3-9de1-67244174a5f8.png)

**Comment by aza547** [comment]
And it shows the wow classic icon I added as a fall back too I guess. Good stuff regardless, I was perhaps more worried about this than I needed to be 😊

**Comment by tdaugaard** [comment]
https://github.com/aza547/wow-recorder/pull/210 this sort of addresses it a bit by moving some logic so the player is always saved, as long as we've seen the appropriate `SPELL_AURA_APPLIED` log events.

**Comment by aza547** [comment]
Stale issue so closing. I think this is working fine.
