### ISSUE TITLE
Test button improvements

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#177]
Test button should:
- Run test even if category is disabled.
- Allow selection of category. 
- Give some popup dialog boxes to say what it's doing i.e. "not running because X" "starting test"

**Comment by aza547** [comment]
First bullet fixed by https://github.com/aza547/wow-recorder/pull/171

**Comment by tdaugaard** [comment]
I have something in the works for this - I was actually planning to make the test button trigger a test suitable for the selected category but thought it might not be super important right now :D

**Comment by aza547** [comment]
Ah that sounds great- definitely doesn't need to be a priority though indeed, was just noting down my thoughts so I don't forget!

**Comment by aza547** [comment]
Seems I regressed the first bullet, which is once again a bug

**Comment by aza547** [comment]
I've made some improvements to the runRetailRecordingTest() function when reworking the UI. 
Easy win in here now to plumb that through the the frontend and allow selection of a category when running the test.

**Comment by aza547** [comment]
I've added category selection here. Doubt I'll rush back to do the rest as that was the main thing here. https://github.com/aza547/wow-recorder/commit/3a9b9cda45715ecd1cb0974a695be97674cbbfc4
