### ISSUE TITLE
[Settings] Disconnected audio source makes drop down show nothing selected

### ISSUE THREAD

**Issue by tdaugaard** [aza547/wow-recorder#183]
### The bug

When an in- or output audio source, that was previously selected, is disconnected (like a pair of headphones) the application will still consider it being selected which results in the drop down for the device type showing nothing being selected.

### To Reproduce
1. Select an in- or output audio source that can be disconnected (USB mic, BT headphones, etc.)
2. Save settings
3. Close the application
4. Disconnect the audio device
5. Start the application and open Settings
6. The selected device will no longer show.

### Expected behavior

Either the audio device type source should be deselected and default to none (preferably) _for the session_ (but not saved!) or the device name should be saved along with the device ID and displayed in the drop down, but grayed out to indicate it's not present, but still selected (preferred).

Perhaps a message can be displayed somewhere if a selected device isn't found to alert the user.

**Comment by aza547** [comment]
Not sure if this is fixed by 3.3.0 - need to check.

**Comment by aza547** [comment]
I fixed this a while back, see https://github.com/aza547/wow-recorder/commit/68dec76b7ab3c91ab099e1bb2040b220ad85a807.
