### ISSUE TITLE
Possible to run two copies of WR and get into a confusing state. 

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#186]
Title. 

![image](https://user-images.githubusercontent.com/32389325/193423319-35f3273f-860c-409e-b78d-871096436f43.png)

Two ideas:
- Enforce only one copy of the app runs at once. That surely is straight forward.
- Include some random part of the log file name so that it's clear which instance of the app is which.

**Comment by tdaugaard** [comment]
Electron has an API for that https://github.com/electron/electron/blob/v0.36.10/docs/api/app.md#appmakesingleinstancecallback

**Comment by tdaugaard** [comment]
Apparently, the new way is https://github.com/electron/electron/blob/main/docs/api/app.md#event-second-instance but they still have an API for it, it just changed to be event based :D

**Comment by aza547** [comment]
Fixed on main.
