### ISSUE TITLE
Beta / PTR support?

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#192]
Is this feasible? How much do we care?

@tdaugaard  has already changed the process watching to accept retail/beta/classic/ptr processes. 

That's probably good enough? beta and PTR are probably really 'types of retail' and uses can just point their retail log path to the installation location.

**Comment by tdaugaard** [comment]
Honestly, I don't think it's worth it to do anything specail for them for now. I'm sure that 1 year from now, the app will look slightly different and perhaps _then_ there's room for it, but for now it seems like waste of time.

**Comment by aza547** [comment]
Agreed. We can re-open in the future if we care to
