### ISSUE TITLE
Should use OBS game capture not monitor capture

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#2]
http://underpop.online.fr/f/ffmpeg/help/gdigrab.htm.gz

Specifically: "title=window_title"

**Comment by alexanderkershaw** [comment]
I tried this. Didn't work out the box. Using title="World of Warcraft" seemed to cause all sorts of issues. Strangely it did seem to record the right window but not the actual app, ended up recording what was behind it. 

Another solution might be to detect screen resolution and just pass that on the command line to the recorder process. 

Probably should also consider the monitor WoW is on and make that a configurable setting.

**Comment by aza547** [comment]
confirmed will correctly capture a different size of monitor fully

**Comment by aza547** [comment]
One of the dragons in this project is the OBS config.
I'd love to work this out / start doing game capture instead of monitor capture.

**Comment by aza547** [comment]
I had a look at this today.

I investigated an other solution to using OBS:
- https://github.com/obsproject/obs-websocket
- https://github.com/obs-websocket-community-projects/obs-websocket-js

Ultimately decided this doesn't work for us based on:
- https://github.com/obsproject/obs-websocket/issues/234

I then had a look at using obs-studio-node again using game_capture, confirmed it's not a player thing. 
- Confirmed the files are genuinely bad, an xxd binary dump of a game_capture recorded video shows a bunch of 1s (must correspond to black video). 
- A similar xxd binary dump of a monitor capture shows real data.

**Comment by KyleCRat** [comment]
👍🏻 for this - Love the app but I use a TV as my primary monitor and it's pretty much locked as screen #2 in windows. Thus making this app always record my second screen. Any chance of a monitor select feature as a holdover until you figure out the window capture?

**Comment by aza547** [comment]
Yeah we should definitely just expose this in the settings page for now.

**Comment by aza547** [comment]
That should be a fairly easy fix (the expose monitor in config, not switch the capture mode). Maybe someone can help with that.

**Comment by aza547** [comment]
I've plumbed the settings through to main.ts, all we need now is someone to expose that in the UI.

**Comment by aza547** [comment]
This is in, coming in next release.

**Comment by aza547** [comment]
Back to the original issue, I wonder if we can use game_capture now I have upgraded OBS. I should try that again.

**Comment by aza547** [comment]
I think @tdaugaard made this work, pretty sure there was a diff in our dev channel on discord at one point.

**Comment by tdaugaard** [comment]
I do indeed - I'll be continuing on this soon when #198 has been merged, as it touches some of the same files.

![image](https://user-images.githubusercontent.com/875107/195092020-d946cf81-10fd-4d2b-950a-a96d8dbca866.png)
