### ISSUE TITLE
[Feature request] Customize audio input/output recording volume

### ISSUE THREAD

**Issue by Liltwix** [aza547/wow-recorder#216]
When recording audio input and output, the input recorded from my mic is louder than I would like compared to the output volume.

It would be convenient if we could adjust the levels of audio input and output to get a nice balance between the two.

For example, NVIDIA ShadowPlay has the following config:
![image](https://user-images.githubusercontent.com/14145397/197632212-39567f8b-78dc-4d31-8b12-913813833cf7.png)

Thanks! Loving the tool so far.

**Comment by aza547** [comment]
Sounds like a good feature indeed and can't imagine it's too difficult.

**Comment by aza547** [comment]
Lots asking for this.

**Comment by aza547** [comment]
![image](https://user-images.githubusercontent.com/32389325/236940029-2ea58d9c-2eaf-414d-b3b0-643fac3f0704.png)
