### ISSUE TITLE
Game_capture getting top left of screen only. 

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#221]
**Describe the bug**
- Large screens on game_capture are recording top left corner only. 
- Monitor capture maybe OK but can't set higher output resolution. 
- Reported by several (atleast 3 users). 

![image](https://user-images.githubusercontent.com/32389325/200085268-580a3f8f-7e93-4c77-94a8-d062d0f4ae13.png)

[2022-11-04_21-48-11 (1).txt](https://github.com/aza547/wow-recorder/files/9942379/2022-11-04_21-48-11.1.txt)
[WarcraftRecorder-2022-11-04 (1).log](https://github.com/aza547/wow-recorder/files/9942380/WarcraftRecorder-2022-11-04.1.log)

![image](https://user-images.githubusercontent.com/32389325/200085551-0f2adac5-88b4-4bb2-8b0e-7fe608d1f72a.png)

![image](https://user-images.githubusercontent.com/32389325/200085566-5c8c513a-f772-4484-abd7-e5e753d9f1d6.png)
[2022-10-31_16-34-02.txt](https://github.com/aza547/wow-recorder/files/9942395/2022-10-31_16-34-02.txt)
[WarcraftRecorder-2022-10-31 (5).log](https://github.com/aza547/wow-recorder/files/9942396/WarcraftRecorder-2022-10-31.5.log)

**Comment by aza547** [comment]
@tdaugaard curious what screen size you have, does this work for you?

**Comment by tdaugaard** [comment]
My monitors are 2560x1440 but via HDMI they support 3840x2160 and downscales it. When I change to 4K on one, I can reproduce the issue.

**Comment by aza547** [comment]
Interesting... along with buying an AMD card do I need to buy a 4k monitor to reproduce this? 

Haven't given this any time since raising. Any suspects as what the cause may be?

**Comment by tdaugaard** [comment]
I tinkered with a for a bit, but I got some weird black videos and then one that worked fine - I suspect that the scaling _needs_ to be set after initializing the OBS recorder and since `lastVideoSize` (or whatever it's called) isn't cleared between videos, perhaps that needs to be done when a recording is stopped such that `watchVideoSize()` will set the scaling again on the next recording even if the video input size hasn't changed.

**Comment by tdaugaard** [comment]
I have an ASUS 1440p 144/170 Hz monitor which supports 4K input via HDMI, but will downscale it - Windows sees it as a 4K monitor so for all intents and purposes, that would make you able to test it, :p

**Comment by aza547** [comment]
Interested in what code you found worked - black screen maybe just the classic leaked OBS instance in dev mode? Looked at this for like an hour today and am none the wiser.

**Comment by tdaugaard** [comment]
I had no leaked OBS instance running (double checked) but I'd probably chalk it up to dev mode shenanigans.

I don't have a lot of time to work on it right now unfortunately :/

**Comment by aza547** [comment]
No worries re time, hobby work never going to be top priority for long :) 

Best idea I had was that somehow we are resetting the scaling and not adjusting it due to a reconfigure - I think that resets scale factors to 1 which might not get updated again if the display size hasn't changed...

**Comment by aza547** [comment]
I think that might actually be a good theory. I've had a skim through all the logs and I think they all have in common that they were launched. I wonder if all we need is `reconfigure()` to reset the  `lastVideoSourceSize` variable so that we don't hit the return in this condition:

```
    if (lastVideoSourceSize && result.width === lastVideoSourceSize.width && result.height === lastVideoSourceSize.height) {
      return;
    }
```

**Comment by aza547** [comment]
> I can confirm it recorded my whole screen now after following those instructions, but I still got the issue that it wont allow me to have an output resolution over 1920x1080 so its really blurry, but its recording the whole screen

**Comment by aza547** [comment]
Fixed on main.

**Comment by tdaugaard** [comment]
I literally did this locally and was 100% convinced I had told you already on Discord. Apparently, I didn't. :( I did the exact same and it "worked for me", for the limited testing I did.

**Comment by aza547** [comment]
hah - balls - well that's encouraging my fix isn't nonsense!
