### ISSUE TITLE
Cannot get arena games to save recordings

### ISSUE THREAD

**Issue by dominicjunik** [aza547/wow-recorder#222]
for WOTLK
Have Auto Combat Logger addon installed.
All Instanced Raid fights are cropped, recorded and saved working as normal.
Cannot get any Ranked arena or Skirmish games to record and save.
Enabled "log arenas" in the arenas tab of the addon, tried setting the delay to 0, 30, and 60 seconds.
Tried disabling all other addons.
Tried old version without the delay feature - 9.2.6
get the messages in chat
AutoCombatLogger: Enabled combat logging
AutoCombatLogger: Delaying disabling combat logging...
AutoCombatLogger: End of Delayed disabling of combat logging...
AutoCombatLogger: Disabling combat logging

**Comment by aza547** [comment]
Hello! Classic arena isn't supported yet so this is expected. Im in the middle of implementing it. You can check it out by building from the loghandlers branch if you'd like, build instructions are in the docs/contributing.md file. It's not fully tested yet though, so if you're not feeling adventurous then just wait for the support  to come in a future release.
