### ISSUE TITLE
OBS didn't signal stop in time

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#244]
![image](https://user-images.githubusercontent.com/32389325/207455900-5dbd1dfd-3e9b-488e-8f5f-dfaf7675f5b4.png)
![image](https://user-images.githubusercontent.com/32389325/207455991-5079b928-15eb-4000-844a-6a8c430a8154.png)

![image](https://user-images.githubusercontent.com/32389325/207455836-512e807f-2713-4047-bc1a-181e2b1d98a9.png)

[2022-12-13_13-59-02.txt](https://github.com/aza547/wow-recorder/files/10222537/2022-12-13_13-59-02.txt)
[2022-12-13_15-42-19.txt](https://github.com/aza547/wow-recorder/files/10222538/2022-12-13_15-42-19.txt)
[WarcraftRecorder-2022-12-13.log](https://github.com/aza547/wow-recorder/files/10222539/WarcraftRecorder-2022-12-13.log)

**Comment by aza547** [comment]
User hit it again with the nvenc encoder:
[WarcraftRecorder-2022-12-13 (2).log](https://github.com/aza547/wow-recorder/files/10232674/WarcraftRecorder-2022-12-13.2.log)
[2022-12-13_15-42-19 (1).txt](https://github.com/aza547/wow-recorder/files/10232675/2022-12-13_15-42-19.1.txt)

Then tried with the obs_x264 encoder on my advice, hit it again:
[WarcraftRecorder-2022-12-14 (3).log](https://github.com/aza547/wow-recorder/files/10232676/WarcraftRecorder-2022-12-14.3.log)
[2022-12-14_12-15-47 (2).txt](https://github.com/aza547/wow-recorder/files/10232677/2022-12-14_12-15-47.2.txt)

![image](https://user-images.githubusercontent.com/32389325/207744258-cf0cda13-867a-4c00-9fab-9eac76c0d32e.png)

**Comment by aza547** [comment]
User is testing if this is related to their custom audio devices.

**Comment by tschokio** [comment]
i am having the same issue, many times, but recording some runs worked without any issues.. should i just provide all the logs i have? or should i try to replicate it and then share this specific log? thanks in advance!

**Comment by aza547** [comment]
Sharing the logs is great - if it re-occurs feel free to share logs and let me know when the error was thrown.

This is a tricky one unfortunately, and goes a bit deeper into the obs-studio-node library we use to bind to OBS from Node. 

Things to try also:
- Do you have any fancy audio / virtual audio devices? That was my suspicion for the original report. Try with no audio devices selected. 
- Try with a software encoder instead of a hardware encoder (see advanced settings).
- Ensure your drivers are up to date.

**Comment by tschokio** [comment]
[logs.zip](https://github.com/aza547/wow-recorder/files/10253864/logs.zip)
[node-obs.zip](https://github.com/aza547/wow-recorder/files/10253865/node-obs.zip)

thanks a lot for your fast reply! :)

in regards to "fancy" audio devices, I'm not sure I'm switiching many times between standard devices while the warcraft recorder is running (between speakers and headset)
other than that.. i'm using the SteelSeries Arctis 7, they have two different output channels, one for gaming and one for chatting but I havent configured that in the warcraft recorder

Input and output is set to (All) in the options

just updated my graphicscard driver, will see if that changes something, if not I'll try the software encoder and will report back if the problem got fixed or not :) 

thanks again!

**Comment by aza547** [comment]
> in regards to "fancy" audio devices, I'm not sure I'm switiching many times between standard audio devices in windows while the warcraft recorder is "minimized" (between speakers and headset)
other than that.. i'm using the SteelSeries Arctis 7, they have two different output channels, one for gaming and one for chatting but I havent configured that in the warcraft recorder

The other user who hit this was using krisp which I've never heard of but seems to be a background noise suppression program. 

I think switching devices is probably a candidate for causing this. Obviously that's pretty unsatisfactory behaviour from WR that I should fix if we can prove that's the problem :) 

> Input and output is set to (All) in the options

Can you try setting it to none and running some? 

> just updated my graphicscard driver, will see if that changes something, if not I'll try the software encoder and will report back if the problem got fixed or not :)

Great. FWIW, the other user did try the switch to software encoding and it didn't help (which might imply that the drivers update won't either - but no guarantee you are hitting the same issue.

**Comment by aza547** [comment]
More changes in 3.3.3 to help address this.
