### ISSUE TITLE
More audio output options?

### ISSUE THREAD

**Issue by Squimbert** [aza547/wow-recorder#245]
**Is your feature request related to a problem? Please describe.**

Yes. I am using Arctis Pro Wireless headset with Sonar enabled, so it is using 2 outputs for the same headset, which makes warcraft recorder record both of them when I have "All" selected for which outputs to record.  This causes an echo and overlapping but staggered outputs.

**Describe the solution you'd like**

The option to select/deselect specific output devices for warcraft recorder to use/ignore.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by aza547** [comment]
Coming in 3.3.0. Closing.
