### ISSUE TITLE
Classic hunter feign death ends arena games early 

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#252]
![image](https://user-images.githubusercontent.com/32389325/208296653-11e1a799-23ee-4b56-ad1f-54a4bdecf261.png)

**Comment by aza547** [comment]
Definitely wrote logic here to end game after a death if we see no more events in the next 20s or so. 

I was worried about games not ending if one kill happens, then the rest of the team /afks. 

I wonder if there is a difference between the flags in classic and retail for feign deaths.

**Comment by ericlytle** [comment]
Here is a log snippet from a game where i was playing with a hunter and you can see he has attacks after a "unit died" event
https://gist.github.com/ericlytle/f32f9820df39670a258800352b4a896f

**Comment by aza547** [comment]
ClassicLogHandler calls `super.handleUnitDiedLine()` (which no-ops and returns if it's a feign death), but then we still go on to call .processArenaDeath() after the call to the super method, that seems wrong at a glance. 

`processArenaDeath()` ends the match if no one is left on either team (but I'm guessing the bug is we we just decrement every feign death) and then end the game after 2, 3 or 5 depending on the bracket...

**Comment by aza547** [comment]
[WoWCombatLog-022424_194216.txt](https://github.com/aza547/wow-recorder/files/14394478/WoWCombatLog-022424_194216.txt)
Another log someone shared.
