### ISSUE TITLE
Recording may start several seconds into arena games

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#26]
Fundamental limitation of how we currently start a recording, due to the WoW combatlog not being written live. It gets flushed periodically (not sure how often/what triggers this). Usually this means recording starts when you get into combat, usually its OK but occasionally you can miss vital positioning moments in the first few seconds. 

Only real idea for a fix is to move to a model where we are permanently recording, and then go back and clip videos to size after the arena match ends. The ARENA_MATCH_END event has the duration of the game in it so it's trivial to get this. Less trivial but surely possible to clip videos. Think this is what SquadOV does after discussion with @ericlytle.

**Comment by aza547** [comment]
https://stackoverflow.com/questions/31046930/how-to-cut-a-video-in-specific-start-end-time-in-ffmpeg-by-node-js

**Comment by aza547** [comment]
Should consider the implications of a fix against the instant replay of videos. The solution should not mean videos are not instantly viewable.

**Comment by ericlytle** [comment]
i was thinking a little about this. Is the delay in combat log caused by the simplecombatlogger addon or does it do it when you manually start combat logs too? something im going to try to test around when i can

**Comment by aza547** [comment]
I suspect it's not caused by the addon, but happy to be proven wrong!

**Comment by aza547** [comment]
The addon pretty reliably seems to start logging as soon as I zone into arena from memory...

**Comment by aza547** [comment]
This is loads better now. But we can still do more.

The current recording strategy is:
- Record screen whenever WoW is running. 
- Restart recording every 5 mins. 
- If an encounter/arena starts, cancel the restart and record till it completes.

This leaves a small window between the start of an encounter/arena that if the 5 minute restarts falls in we'll still have this problem. For example, if the gates open and 2 secs later the restart triggers, then 2 secs later the ARENA_MATCH_START event hits. 

The fix to this is to add some logic to handle this scenario by stitching an old buffer video onto the new one. We only delete buffer recording files that are not the most recent, so it will always be available. 

Might try tackle this in a few weeks but expect this to be drastically improved as of 2.5.0.

**Comment by aza547** [comment]
Discord request for some extra time at start of raid recording to grab pull timer.

**Comment by aza547** [comment]
Closing this as I think it's good enough as it is.
