### ISSUE TITLE
Warcraft Recorder not starting with Windows

### ISSUE THREAD

**Issue by Squimbert** [aza547/wow-recorder#272]
**Describe the bug**

Warcraft Recorder isn't starting with Windows, even when the settings in the software are enabled and it is also enabled in Windows startup apps.

**To Reproduce**

All settings enabled... restart PC. Have to start Warcraft Recorder manually.

**Expected behavior**

Warcraft Recorder should start automatically when Windows starts when the settings are enabled.

**Screenshots**

**Additional context**

**Comment by aza547** [comment]
Hm, strange. Looks like we are updating Windows start-up config. It correctly toggles with the setting change:

![image](https://user-images.githubusercontent.com/32389325/211107060-99cfa1bd-707f-4304-b73c-3a035aba81d9.png)

...but then it doesn't actually start with Windows despite looking like it should.

**Comment by aza547** [comment]
> One of the reasons why a program might not launch is because it requires administrator permission to run. To avoid this problem, you can [use Task Scheduler to launch the program](https://www.makeuseof.com/tag/how-to-automate-windows-programs-on-a-schedule/) every time with administrative privileges.

Might be this, would make it a recent (3.3.0?) regression.

**Comment by aza547** [comment]
https://github.com/aza547/wow-recorder/commit/8a72524c10f02def1707a98c363493a1c0688bc7

**Comment by Squimbert** [comment]
I created a bandaid fix by adding it to task scheduler, but with a 30 second delay after startup. Not sure why it needed the extra time to not fail starting up but i hope this helps in figuring out what is causing the issue.

**Comment by aza547** [comment]
I've reverted the change made here on main: 8a72524c10f02def1707a98c363493a1c0688bc7
