### ISSUE TITLE
[Feature Request] Add option to delay the stop of recording

### ISSUE THREAD

**Issue by JH0Ni-github** [aza547/wow-recorder#286]
Recording apparently stops instantly when for example an encounter success event fires. Would be nice to have the achievement pop-ups and kill reactions for mythic raid bosses recorded. (: Possibly add an option to delay set amount of seconds (15-30?) or let user define their own value.

**Comment by aza547** [comment]
This was bugged in pre-3.3.3 versions. 

In the code this is called the "overrun" and should now be working in 3.3.3.

Raid encounters will overrun by 15s, arenas by 3s, etc. 

See for ex. https://github.com/aza547/wow-recorder/blob/main/src/activitys/RaidEncounter.ts#L29. 

I'm closing this as a result, if you think it's not working, please re-open. 

Thanks!
