### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#3]
https://www.reddit.com/r/ffmpeg/comments/fjv8fg/optimizing_cpu_usage_for_screen_recording/

**Comment by alexanderkershaw** [comment]
https://trac.ffmpeg.org/wiki/Capture/Desktop

See "Hardware Encoding" section. Need to do conditionally for GPU type?

**Comment by alexanderkershaw** [comment]
OBS thread:
https://obsproject.com/forum/threads/command-line-options-scripting-for-start-recording-on-startup-split-recordings-on-time-filesize.80659/#:~:text=The%20command%20line%20parameters%20for,up%20with%20a%20single%20file.

`.\obs64.exe --startrecording --minimize-to-tray` does work but maybe not ideal, window briefly opens over screen.

**Comment by alexanderkershaw** [comment]
Have implemented hardware encoding for NVIDIA and AMD GPUs via FFMPEG in 1.0.2. Still to investigate libobs usage, but expect that's a longer term goal.

**Comment by aza547** [comment]
Have done quite a lot of research into this now. It's clear the correct way to go is via libobs.

I've started implementing this on the libobs branch. There is node bindings for libobs available here:
- https://github.com/stream-labs/obs-studio-node

With example:
- https://github.com/Envek/obs-studio-node-example/blob/master/index.js

**Comment by aza547** [comment]
Now using libobs.
