### ISSUE TITLE
How can we gracefully handle DCs mid recording?

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#30]
Currently I think we will just record for ever as e.g. no ARENA_MATCH_END event will fire.

Should consider other content types too. 

Think it's tricky. Maybe something OK but not great like a 20 min timeout to avoid really ugly scenarios?

**Comment by aza547** [comment]
What about something like if no writing to the combatlog in 60s we stop recording?

**Comment by arbalzer** [comment]
I simulated a DC by  removing my ethernet cord while in game and monitored the logs folder for file changes. The only file that actually gets any updates when disconnected seems to be the Voice.log file. This file gets cleared and updated with one line upon login:
> 8/30 14:24:05.888  Voice Log Initialize.

and then on disconnected a few more lines are added about the disconnection:

> 8/30 14:24:05.888  Voice Log Initialize.
8/30 14:24:05.888  WowConnectionNet: Initialize
8/30 14:24:05.911  AttemptMakeSocketPair: bound to 1 / WoW Loopback.19424.2064720106
8/30 14:24:05.911  MakeSocketPair attempt: 1, 0, 0, 0
8/30 14:24:06.015  VoiceProxy attempting to listen on 127.0.0.1:6724
8/30 14:24:16.677  WowConnection::CheckAccept (on 127.0.0.1:6724) -- Connection from 127.0.0.1:54018 accepted
8/30 14:24:16.677  WoW client has connected to proxy
8/30 14:25:40.195  Transport disconnected.  Error [7], Reason [connection disconnected unexpectedly]
8/30 14:25:40.195  Last client closed, stopping proxy.
8/30 14:25:40.250  WowConnectionNet: Shutdown
8/30 14:25:40.250  Voice Log Destroy.

Could possibly monitor this file for changes to detect a disconnect and stop recording. Then also resume recording on successful reconnect (Voice.log cleared).
I wasn't able to find a way to disable in-game voice chat in the settings, so I suspect that these log files should be present for everyone.

**Comment by aza547** [comment]
Another idea that I'm on the fence about: Add a force stop recording button, useful for cases like DC etc.

**Comment by tdaugaard** [comment]
> What about something like if no writing to the combatlog in 60s we stop recording?

I have that in one of my currently open PRs :)

> Another idea that I'm on the fence about: Add a force stop recording button, useful for cases like DC etc.

We've added this!

**Comment by aza547** [comment]
Also maybe https://github.com/aza547/wow-recorder/issues/278 can eventually help here

**Comment by aza547** [comment]
This hasn't really posed much of a problem it seems. Timeouts/queueing mechanisms should cover us.
