### ISSUE TITLE
The specified module could not be found

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#328]
> I did a fresh install on a new pc today and I cant get the program to start up. After install, I run the program and get this error. No application opens or icon in system tray. I have to go to task manager to end the process.
I have tried uninstalling and reinstalling 3.5.1, 3.5, and 3.4.0. Same error every time.

https://media.discordapp.net/attachments/1004860869760516218/1076568576141566082/image.png

https://stackoverflow.com/questions/66609529/electron-builder-installer-a-javascript-error-occurred-in-the-main-process-err

https://github.com/aza547/wow-recorder/actions/runs/4213378035

**Comment by aza547** [comment]
Only seen by one person so probably won't investigate further.

**Comment by Robvdhout** [comment]
I get the exact same issue

**Comment by MK-NG** [comment]
First time installer. Same issue.

**Comment by aza547** [comment]
Current theory is some dll is missing on windows:
https://github.com/stream-labs/obs-studio-node/blob/staging/obs-studio-client/dependencies/obs_studio_client.node.txt

**Comment by aza547** [comment]
If we can confirm this is true, might be missing this:
https://github.com/stream-labs/desktop/pull/1913/files

**Comment by MK-NG** [comment]
![depend](https://user-images.githubusercontent.com/38420388/234026512-49277e99-9969-4b1c-b1dd-28776a37c747.png)

Mines slightly different(worse 😢)

**Comment by aza547** [comment]
Thanks both. That's interesting... the node.exe file is certainly meant to be installed automatically.

I suspect you can get it working by...
@Robvdhout - install NodeJS manually https://nodejs.org/en/download
@MK-NG - install NodeJS manually https://nodejs.org/en/download and https://aka.ms/vs/17/release/vc_redist.x86.exe (from [here](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170))

Can you try that and let me know how you get on? I'll try to understand how this has happened meanwhile...

**Comment by Robvdhout** [comment]
That seems to have allowed me to run it. I've setup the folders and the alert icon is gone, but the test button does nothing (after selecting test type)

**Comment by aza547** [comment]
Got wow open? Think the test button does nothing if not

**Comment by Robvdhout** [comment]
That solved that indeed, but now I see that the test ran in the log file 

```
  filename: 'Sepulcher of the First Ones, Lihuvim [M] (Kill)',
  relativeStart: 34.976
}
[2023-04-24 16:48:21.904] [info]  [VideoProcessQueue] Now processing video C:\Warcraft Recorder\.temp\2023-04-24 16-47-08.mp4
[2023-04-24 16:48:21.905] [info]  [VideoProcessQueue] Raid encounter was too short, discarding
[2023-04-24 16:48:21.905] [info]  [VideoProcessQueue] Finished processing video C:\Warcraft Recorder\.temp\2023-04-24 16-47-08.mp4
[2023-04-24 16:48:21.907] [info]  [VideoProcessQueue] Video processing queue empty
[2023-04-24 16:48:21.908] [info]  [SizeMonitor] Running, size limit is 200 GB
[2023-04-24 16:48:21.909] [info]  [SizeMonitor] Deleting 0 old video(s)
```
And I see the mp4 in that location, but it's not showing up anywhere in the warcraft recorder GUI

**Comment by aza547** [comment]
> Raid encounter was too short, discarding

Try a different test category, or reduce the "Minimum Encounter Duration (sec)" setting. I forget what the test duration is hardcoded to, clearly the test button needs some improvements...

**Comment by Robvdhout** [comment]
default in my settings is 15 seconds, but the Mythic+ test worked, tyvm Alex

**Comment by aza547** [comment]
Also I wonder if the electron installer hasn't installed node.exe because it's elsewhere on your PC, but that's not being picked up at runtime? It seems unlikely you both genuinely don't have node.exe (at least I can see @MK-NG is using discord, which uses node.exe too). 

Could you search your PC for node.exe and see what hits you get? Recommend [everything](https://www.voidtools.com/) for that. Mine for example...

![image](https://user-images.githubusercontent.com/32389325/234036148-470e8bbf-1b85-4f63-bb12-7e1fe34d5c73.png)

**Comment by Robvdhout** [comment]
![image](https://user-images.githubusercontent.com/2537415/234037741-21bcf47f-ba36-4271-9c49-c88f819621f1.png)

**Comment by aza547** [comment]
Had a fiddle around with this. Purged node and the c++ libraries from my PC and reproduced the problem. I then reinstalled the C++ libraries only, and the app works fine. Despite that, dependencies still claims it's missing. 

![image](https://user-images.githubusercontent.com/32389325/234055466-2e0a2caa-21d0-481b-9305-ecb1d949321b.png)

I also installed streamlabs and found it prompted me to install the C++ libraries as part of my installation. Found some [code](https://github.com/stream-labs/desktop/blob/master/installer.nsh#L2) in the streamlabs desktop repository that looks responsible for that.

**Comment by aza547** [comment]
So guessing somehow node.exe isn't required, but the C++ libs are. Not sure how that explains the behaviour above, particularly in Rob's case where installing NodeJS fixed it. Perhaps node.exe isn't required, but something in the C++ libs is required that isn't identified by dependencies.

**Comment by aza547** [comment]
Perhaps if you have time folks, you could remove NodeJS from your PCs, and install the C++ libs only from [here](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) and confirm it still works?
