### ISSUE TITLE
Request: Chat Overlay

### ISSUE THREAD

**Issue by janmkrueger** [aza547/wow-recorder#331]
I would love a way to add a Overlay over my Chat, so i can directly stream some of the recorded footage without exposing my chat/whispers.

Maybe there is a way already im overlooking?

**Comment by aza547** [comment]
See https://github.com/aza547/wow-recorder/issues/46 - probably not going to do this anytime soon I'm afraid, but would be happy to accept it if you fancy submitting a PR
