### ISSUE TITLE
Add Settings to Change Buffer Time before and after content (specifically Solo Shuffle)

### ISSUE THREAD

**Issue by RaphanW** [aza547/wow-recorder#335]
I like to open my talents and the lobby window before solo shuffle round 1 so I have that in the recording. 3 seconds is a little crunched, 5 or 10 would be ideal.
Similarly, I like to sort the scoreboard after the end of solo shuffle round 6, so I have that in the recording.  3 seconds is a little crunched, 5 or 10 would be ideal.
Choose reasonable limits on the maximum (maybe 10 or 15 seconds) so someone doesn't accidentally add 100000000 seconds to their recording.

Right now I try to do the above quickly, but it would be more relaxed with a bit more time.

**Describe the solution you'd like**
Suggested UI:
Under the advanced tab (or content tab) of settings, add Variables
"Buffer before start (seconds)" and a text field, with default 3. (set to 0 if below 0, set to 15 if above 15).
"Buffer after end (seconds)" and a text field, with default 3. (set to 0 if below 0, set to 15 if above 15)

Under the hood, use those variables rather than the default of 3 seconds.

Thanks for the addon! If I am the only one who would want this, I understand if it's not a high priority. Maybe others would like it as well.

**Comment by aza547** [comment]
Thanks for the suggestion. Curious why you don't just pause on the talent pane / score screen if you want to take a close look?

Plumbing these through as config options is certainly possible, but also we could just make the defaults a bit longer.

**Comment by RaphanW** [comment]
I meant that it's a bit crunched to load up talents at 3, close them, load up leader-board, close it, and be ready by 0. Similarly to do a few sorts of the leader-board at the end in 3 seconds. 

It's not a huge deal but it is my only annoyance with the program.

**Comment by aza547** [comment]
Sorry - not planning to do anything here as not convinced the benefit is worth the effort investment.
