### ISSUE TITLE
undefined - Last boss NO

### ISSUE THREAD

**Issue by th33ch0** [aza547/wow-recorder#384]
**Describe the bug**
In the recording, the last boss is listed as "undefined".

**To Reproduce**
1. Run NO
2. Get to last boss
3. Finish Dungeon
4. Review VOD and hover orange bar.

**Expected behavior**
List boss as "Balakar Khan"

**Screenshots**
![image](https://user-images.githubusercontent.com/13324849/234768428-aa643308-a285-4c88-80f3-e1521f9a4938.png)

**Additional context**

**Comment by aza547** [comment]
thanks for the issue! hopefully an easy fix
