### ISSUE TITLE
Improve Audio Selection Menu

### ISSUE THREAD

**Issue by th33ch0** [aza547/wow-recorder#385]
**Is your feature request related to a problem? Please describe.**
The step where you have to click off of the dropdown list is not intuitive.

**Describe the solution you'd like**
Have an "Accept" or "Okay" and "Cancel" button at the bottom of the selection window.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by aza547** [comment]
Fair report - agree that would be an improvement.

**Comment by aza547** [comment]
Lots of changes here in the coming release but this isn't actually improved. Keeping the issue.

**Comment by aza547** [comment]
Realistically not going to improve this now, I'm happy enough with how it is.
