### ISSUE TITLE
video still playing after pressing the cross

### ISSUE THREAD

**Issue by qstrql** [aza547/wow-recorder#388]
**Describe the bug**
ver v3.10.1
When the windows is open, and a video is replaying, clicking the cross minimize to tray but the audio keeps playing.

**To Reproduce**
1. Open Warcraft Recorder
2. Open any video and press play
3. Click the cross top right
4. Audio keeps playing,

**Expected behavior**
I would expect the sound to cut after closing the windows but it does not.

**Comment by aza547** [comment]
I guess it's playing from the system tray. Agree it should pause.
