### ISSUE TITLE
Installer Bug. Still Detects Main App as Running.

### ISSUE THREAD

**Issue by NathanPrice** [aza547/wow-recorder#396]
Hi, this isn't too big of an issue. Just something I find a bit annoying and would be a nice quality of life change if it gets fixed. 

Whenever a new release of the app is pushed out and I run the installer beforehand I usually alt f4 the app since it's quick and easy for me. For whatever reason the installer still detects that the app is open and won't proceed unless I manually re-open the app, go to the app try, right click it and select quit. This has happened for several versions in a row and not sure when it started.

Could just be some other remnant of the app running if you don't do it through the app try or a bug somewhere with the installer itself not 100% sure but just thought I'd mention it regardless since it gets pretty annoying forgetting about it and having to re-open it just to close it again for the installer to work but not too big of a deal just thought I'd mention it. Also yes I make sure to check task manager as well and the only thing listed there running is the installer itself as far as I know as nothing else comes up with the same name.

OS I'm running is Windows 11 Enterprise 22H2 22621.1555

**Comment by NathanPrice** [comment]
Thanks for getting back with me. That's strange, don't entirely sure what could be causing it. Also each time I've upgraded and this happens it's only from 1-2 versions earlier with the one I did recently being from a 3.10.X version to 3.11. Dont think it's OBS either because it isn't in my task manager when this happens. I can post about it again here when a new version gets pushed out to get more details because it's kind of hard to diagnose since there's no error message and no logs to look atthrough to narrow it down.

**Comment by aza547** [comment]
Logs will probs help if you can reproduce it, alt + f4ing should go through the normal quit code which shuts down OBS (weird if it's not in your task manager though). 

For example when I alt + f4 I see as the last few lines in my logs:

> [2023-05-03 20:15:52.685] [info]  [Main] User closed app
[2023-05-03 20:15:52.685] [info]  [Main] Running before-quit actions
[2023-05-03 20:15:52.686] [info]  [Main] Shutting down OBS before quit
[2023-05-03 20:15:52.686] [info]  [Recorder] OBS shutting down c4489e06-06d5-458b-990f-4d70b24c495f
[2023-05-03 20:15:52.710] [info]  [Recorder] OBS shut down successfully

**Comment by aza547** [comment]
Closing as not heard back - feel free to re-open if you can reproduce
