### ISSUE TITLE
Record only WoW Game audio not entire speaker output

### ISSUE THREAD

**Issue by DS9x** [aza547/wow-recorder#411]
**Is your feature request related to a problem? Please describe.**
Record only WoW Game audio only not entire speaker output. Currently it grabs all output audio like discord, twitch streams, video streaming in BG, music playing anything i hear form my speakers. I wold like separate options on what to enable to capture.

**Describe the solution you'd like**
I would like to only record WOW audio and have a option to enable or disable discord sound to be added or not to capturing or on a per app basis.

**Describe alternatives you've considered**
Its either all or none with audio and this program.

**Additional context**

**Comment by aza547** [comment]
This would be a nice feature but I suspect is quite a challenge to implement.
Meanwhile you can use a virtual audio mixer to do this, e.g. https://github.com/aza547/wow-recorder/blob/main/docs/FilterAudio.md.

**Comment by JoeMShanahan** [comment]
Is this not supported by OBS?

**Comment by aza547** [comment]
Interesting. I'll have a look sometime to see if that is exposed over the node bindings. Thanks!

**Comment by aza547** [comment]
I did have a look at this yesterday, this isn't exposed through the OSN package we use so isn't possible without major changes. Closing as a result. Sorry!
