### ISSUE TITLE
Tagging feature

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#421]
For adding a short description to videos. / filtering on it.

**Comment by kjstanfield** [comment]
Or possibly just anyway to add notes, I frequently bookmark raid pulls to view after raid and usually keep a notepad open on the side to jot down what I bookmarked it for.

**Comment by aza547** [comment]
I've added this in the above commit. Feedback welcome. Also see preview here:
https://discord.com/channels/1004860808737591326/1014227613897736233/1206304353762410566
