### ISSUE TITLE
Push to Talk/Record extra audio config

### ISSUE THREAD

**Issue by amzeus1976** [aza547/wow-recorder#424]
I absolutely love this software gone are the days I forget to set up obs so we can review stuff just M+/Raid 

how ever as someone that has bad asthma I seem to have inadvertently started producing ASMR content, with OBS I used to use the push to talk/record-setting  with the same key bind as the comms software (mostly Discord)

so id really like to see that feature

multiple input steams would be grand too but that down the list

**Comment by aza547** [comment]
See https://github.com/aza547/wow-recorder/issues/125
