### ISSUE TITLE
robotic audio

### ISSUE THREAD

**Issue by Squimbert** [aza547/wow-recorder#426]
**Describe the bug**
Video quality is great. Recording at 60fps and 1440p.  Using 30Mbps Bitrate.  The audio is almost always robotic sounding.

**To Reproduce**
Record.

**Expected behavior**
Clear audio, as my game and mic sound clear outside of the recordings.

**Additional context**
Is there a way to increase audio bitrate?  Anything that can be done?

**Comment by aza547** [comment]
See https://github.com/aza547/wow-recorder/issues/298
