### ISSUE TITLE
Add Mythic+ recording support [Logs wanted]

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#43]
See https://github.com/aza547/wow-recorder/issues/6

**Comment by aza547** [comment]
Lots of people are asking for this now. Pretty high on the priority list.

**Comment by aza547** [comment]
It would help greatly if people could submit their M+ logs here, so I can build an allow-list of internal ZONE_CHANGE events that shouldn't stop the recording.

**Comment by aza547** [comment]
Should consider adding a "boss only" mode, or having some recognition of boss encounters to save people searching long vods. We could watch the combat log for damage events vs a certain mob etc. There might even be actual boss pull events but wouldn't be suprised if not.

**Comment by DThielke** [comment]
The boss events you're looking for are "ENCOUNTER_START" and "ENCOUNTER_END".

**Comment by aza547** [comment]
https://github.com/Nnoggie/MythicDungeonTools/blob/bf3bd4b83c77df7425473927983ab7342982e720/MythicDungeonTools.lua#L2613

>MDT.zoneIdToDungeonIdx = {
  [934] = 15, --atal
  [935] = 15, --atal
  [936] = 16, --fh
  [1004] = 17, --kr
  [1039] = 18, --shrine
  [1040] = 18, --shrine
  [1162] = 19, --siege
  [1038] = 20, --temple
  [1043] = 20, --temple
  [1010] = 21, --motherlode
  [1041] = 22, --underrot
  [1042] = 22, --underrot
  [974] = 23, --toldagor
  [975] = 23, --toldagor
  [976] = 23, --toldagor
  [977] = 23, --toldagor
  [978] = 23, --toldagor
  [979] = 23, --toldagor
  [980] = 23, --toldagor
  [1015] = 24, --wcm
  [1016] = 24, --wcm
  [1017] = 24, --wcm
  [1018] = 24, --wcm
  [1029] = 24, --wcm
  [1490] = 25, --lower mecha
  [1491] = 26, --upper mecha
  [1493] = 26, --upper mecha
  [1494] = 26, --upper mecha
  [1497] = 26, --upper mecha
  [1663] = 30, --halls of atonement
  [1664] = 30, --halls of atonement
  [1665] = 30, --halls of atonement
  [1666] = 35, --necrotic wake
  [1667] = 35, --necrotic wake
  [1668] = 35, --necrotic wake
  [1669] = 31, --mists of tirna scithe
  [1674] = 32, --plaguefall
  [1675] = 33, --sanguine depths
  [1676] = 33, --sanguine depths
  [1677] = 29, --de other side
  [1678] = 29, --de other side
  [1679] = 29, --de other side
  [1680] = 29, --de other side
  [1683] = 36, --theater of pain
  [1684] = 36, --theater of pain
  [1685] = 36, --theater of pain
  [1686] = 36, --theater of pain
  [1687] = 36, --theater of pain
  [1692] = 34, --spires of ascension
  [1693] = 34, --spires of ascension
  [1694] = 34, --spires of ascension
  [1695] = 34, --spires of ascension
  [1697] = 32, --plaguefall
  [1989] = 37, --tazavesh streets
  [1990] = 37, --tazavesh streets
  [1991] = 37, --tazavesh streets
  [1992] = 37, --tazavesh streets
  [1993] = 38, --tazavesh gambit
  [1995] = 38, --tazavesh gambit
  [1996] = 38, --tazavesh gambit
  [606] = 40, --grimrail depot
  [607] = 40, --grimrail depot
  [608] = 40, --grimrail depot
  [609] = 40, --grimrail depot
  [595] = 41, --iron docks
  --https://wowpedia.fandom.com/wiki/UiMapID
}

**Comment by Skullcan** [comment]
NIce work, I'll just leave this here to get notified when it supports m+!

**Comment by csutcliff** [comment]
I would think CHALLENGE_MODE_START / CHALLENGE_MODE_END would be enough for basic m+ support, ignore the ZONE_CHANGE events. We can expect people to stop logging if they leave a key early so a reasonable combat log timeout should handle those instances whilst still allowing people to jump outside to change gear/talents etc.

**Comment by aza547** [comment]
Some sample logs here: https://drive.google.com/drive/folders/1eQfCsdRyemFKHtyloxc378izgBLbAt_T

Too big to attach sadly, I've saved them locally in case we lose access to the google drive.

**Comment by tdaugaard** [comment]
I'm low key working on this, but it's not an easy feat as the code is highly centered around PvP/Raids. It's not impossible, though.

Adding the new (old) dungeons (images, zone IDs/names, encounter names, etc.) and such.

It doesn't really require anything else but the ENCOUNTER_START and ENCOUNTER_END lines from the log, as it contains both the encounter ID, zone ID, difficulty ID (8 = Mythic Keystone), and success flag (for _END).

**Comment by tdaugaard** [comment]
> I would think CHALLENGE_MODE_START / CHALLENGE_MODE_END would be enough for basic m+

Only if you want to record the entire dungeon. My thinking was that whether Mythic+ should trigger a recording of the entire dungeon or only the  boss encounters could/should be a setting. I can definitely see how having footage of trash pulls _could_ be useful.

Another nice-to-have, albeit a bigger undertaking, would be to record the entire dungeon but have time stamps for the boss encounters (a bit like WarcraftLogs does it) such that you could quickly seek to them - it'll take up quite a bit more space for the recording of course.

**Comment by csutcliff** [comment]
Trash in Mythic plus is at least as important as the bosses depending on the week. I cannot conceive of a situation where someone cares enough to want to record the gameplay but then doesn't want half of the content. The recordings are only useful as a whole run imo.

**Comment by mangleboot** [comment]
Just chiming in to agree with the above post stating m+ trash is equally as (if not more) important than the bosses on m+. Recording size will be huge, i reckon, but the complete run is what would be of interest in regard to M+.

**Comment by tdaugaard** [comment]
> Trash in Mythic plus is at least as important as the bosses depending on the week. 

Yeah, I figured that.

> Recording size will be huge, i reckon, but the complete run is what would be of interest in regard to M+.

I used to record my dungeon runs with OBS in the highest quality and a run of Spires of Ascension (37 minutes) was about 11.4 GB.

How would you like it implemented, like ... record everything and timestamp the bosses and interpolate the trash segments between them for easy seeking OR record separate videos as such:

`CHALLENGE_MODE_START` = begin dungeon, start recording a trash segment
`ENCOUNTER_START` = stop recording trash (no overrun), and start recording a boss encounter
`ENCOUNTER_END` = stop recording boss encounter (2 sec overrun), start recording trash segment
`CHALLENGE_MODE_END` = end dungeon, end recording

Then, delete the last video if there were no `UNIT_DIED` lines detected after the last `ENCOUNTER_END` (indicating that no additional trash was killed after)?

I think perhaps the latter would be ideal (and much easier to implement) in order to make it easy to upload/share the clips from a given segment, but I'd like to hear your take on it.

**Comment by aza547** [comment]
Appreciate the input/discussion here. I'll try catch up properly later today. Some initial thoughts:  
- I do strongly feel that we need full recordings of dungeons rather than boss only. 
- Having bosses split out/seekable would be a brilliant feature (as it would be in all content types for other notable events)
- Feels like a future enhancement to me rather than something to solve now.
- Not sure how much I care about 11GB files for now. Disk space is cheap. 
- There is an easy future enhancement to make quality configurable for those who are struggling for space. 

Thanks for looking at this. It's great to have other people involved. I think both @tdaugaard and @csutcliff are looking at this - be sure to chat to each other to avoid duplicating effort!

**Comment by FrankC37** [comment]
Here is a log from a recent M+. I have a lot more archived on my machine but wasn't sure how "clean" then should be.
This one is probably peak cleanliness as far as not having a lot of excess zone chances etc.. just the key itself.
[Mechagon Workshop Log.txt](https://github.com/aza547/wow-recorder/files/9491006/Mechagon.Workshop.Log.txt)

**Comment by tdaugaard** [comment]
I'm pretty far in my fork: https://github.com/tdaugaard/wow-recorder/tree/feature/implement_mythic_plus_support

I'm implementing it in the way I wrote earlier on, with virtual video segments recorded for trash/boss segments that can be seeked in the video (using the HTML5 player fragment format: `<source src="...#<start>,<end>" />`)

Basically, it records  one full video file and saves more metadata with relative timestamps to easily seek.
