### ISSUE TITLE
Resulting video has a weird sharp look to it, as if it has some kind of filter

### ISSUE THREAD

**Issue by vaisest** [aza547/wow-recorder#432]
**Describe the bug**
Here's an image:
![image](https://github.com/aza547/wow-recorder/assets/4550061/c0b2ca68-b687-4eba-8924-29cd489a9814)

**To Reproduce**
Record video normally. I have these settings: 
![image](https://github.com/aza547/wow-recorder/assets/4550061/7bed987c-d349-46f9-a9c0-e918bcd83851)
![image](https://github.com/aza547/wow-recorder/assets/4550061/c3751e25-0d28-44ca-a8cf-7e5c340421cc)

**Expected behavior**

**Screenshots**

**Additional context**
I am playing in Windowed mode. It should be in 1440p which is the same as the scene resolution, but it is possible I have accidentally dragged the window to slightly change the size.

**Comment by aza547** [comment]
![Screenshot_20230719-072017.jpg](https://github.com/aza547/wow-recorder/assets/32389325/3e3588f9-e157-40c2-b39a-3e21939ad903)

Looks like this?

**Comment by vaisest** [comment]
It's probably that. It's be nice if it was mentioned in the app or even if window capture was supported.
