### ISSUE TITLE
App Crashing after M+ (JavaScript Error)

### ISSUE THREAD

**Issue by mikeyv19** [aza547/wow-recorder#441]
**Describe the bug**
After I run my first M+ after logging into WoW, the app crashes with an error. I don't get any more errors if I keep running M+; however, the nothing is getting recorded.

**To Reproduce**
I noticed this error started after my computer crashed on night mid-mythic. Was halfway through a M+ and my power got cut. I rebooted and logged back into WoW to finish the Mythic and had this error pop up. It pops up every time now and I haven't been able to record anything since that time (two weeks ago).

I have not tried PVP or anything else...only M+.

**Screenshots**
Link to error:
[https://imgur.com/a/idQARGm](https://imgur.com/a/idQARGm)

**Additional context**
I have Warcraft Recorder installed on my C: drive SSD. Videos are beings saved to my E: drive HDD. Have been using this app for months with no issues. Tried to redownload and run the installer again, but that did not fix.

**Comment by aza547** [comment]
Can you share the WR log from this day please?

**Comment by mikeyv19** [comment]
- Can you share the WR log from this day please? - **Is there a file path to the logs? The button in the lower right hand corner of the app does not do anything when I click it.**
- Does this happen all the time? **Yes, Sept 11 was when I had the power cut. We were on the last boss of NL when the power cut happened. I'll also add that the only thing that ended up getting recorded from that run was from the moment I relogged after the power cut and completed the mythic. No prior part of that instance was saved.**
- If you restart your app, does it happen again? - **Next time I run a mythic, I'll test and see what happens if I restart WR prior to my first run and see if I get any different results. I think I've tried relaunching it after I get the error, but then nothing records. I'll see what happens if I reboot prior to any errors/mythics.**

**Comment by mikeyv19** [comment]
Just to follow up if this helps. I tried launching WoW, logged in. Exiting WoW Recorder completely. Starting WoW Recorder back up. Ran an M+, and got the same error at the end of my M+.

**Comment by aza547** [comment]
Logs button should work, it's weird that it doesn't. I'll find the path later for you when I'm at the PC, but it's the same path as the installation roughly (you can probs follow the shortcut to find it?)

**Comment by aza547** [comment]
Log location:
![image](https://github.com/aza547/wow-recorder/assets/32389325/56ed301d-efbd-4fee-a24b-332738c40c35)

**Comment by mikeyv19** [comment]
Thanks for all your help...think the actual problem sat between the keyboard and the chair (me)...The drive that I was pointing the recordings to had ran out of space. So, the error was actually being caused because there wasn't enough space to save the video.

I don't have the logs as I had reinstalled since then, but I deleted some of the older videos and have been running Mythics, getting recording, all with no issue.

Sorry for the confusion. I guess the timing of the power cut and filling up the drive at the same time threw me off here.

**Comment by aza547** [comment]
Ah - no problem. FYI handling this better this is also tracked here: https://github.com/aza547/wow-recorder/issues/311.

You can also use the max storage setting to keep the disk size in check, but it needs to be small enough that it triggers before your disk fills.
