### ISSUE TITLE
Using microphone even when idle

### ISSUE THREAD

**Issue by ghetolay** [aza547/wow-recorder#453]
### Describe the bug
It seems that Warcraft Recorder is constantly recording my microphone.
I don't know if that's actually the case or not but, on Windows, as long as Warcraft Recorder is running I have the microphone icon on the taskbar warning me that `obs64.exe is using my microphone`.

### To Reproduce
Just have Warcraft Recorder running and not recording.

### Expected behavior
This icon should only appear when Warcraft Recorder is recording and not when it's idle.

**Comment by aza547** [comment]
WR should release your microphone when WoW is closed. There is code specifically targeted at that. Certainly a bug if it's using the mic when WoW is closed, but I've tested this quite thoroughly as it was preventing Windows from sleeping at a time, which was a further annoyance. 

Can you confirm if this is happening when WoW is closed? The buffer recording is always running when WoW is open (TL;DR combat log is weird and doesn't always write in real time).

**Comment by ghetolay** [comment]
I did some more testing :

When I launch WR (manually or at PC startup) I got the icon and indeed my computer does not go into sleep mode
When I run WoW, nothing changes (as expected from what you're saying)
but as soon as I close WoW then microphone is released, even if I run WoW for a few seconds.

So I guess some code reacting at WoW close event is releasing the microphone correctly while some init code is holding it forever.

**Comment by aza547** [comment]
Agree there is a bug here. I think the issue is here: https://github.com/aza547/wow-recorder/blob/main/src/main/Manager.ts#L352. 

This call unconditionally attaches the audio devices to the scene and is called by the Manager class on launch of the app and every change to audio settings. Think a sensible fix is to expose the state of the wow process from the Poller class and check that, e.g.

```
if (this.poller.isWowRunning)
{
  this.recorder.configureAudioSources(config);
}
```
