### ISSUE TITLE
Media keys will start video when app is minimized

### ISSUE THREAD

**Issue by vaisest** [aza547/wow-recorder#457]
**Describe the bug**

**To Reproduce**
1. Open app
2. Start playback
3. Close app (to tray)
4. Press media keys

**Expected behavior**
I would expect for nothing to happen when the app is minimized. I would actually even prefer for media keys to not do anything when the app is open.

**Comment by aza547** [comment]
Fixed by https://github.com/aza547/wow-recorder/pull/528
