### ISSUE TITLE
Records every type of content regardless of configuration

### ISSUE THREAD

**Issue by rationalcoder** [aza547/wow-recorder#459]
I followed the setup instructions on Windows 10, configured the app to only record 2v2, 3v3, and Solo Shuffle, ran the test, and it worked, but it records all types of content.

The only thing I can imagine is that a restart is required and I didn't do that? I also can't delete vods through the UI, but I guess that's a separate issue.

**Comment by aza547** [comment]
> I followed the setup instructions on Windows 10, configured the app to only record 2v2, 3v3, and Solo Shuffle, ran the test, and it worked, but it records all types of content.

Thanks - I'll look into this when I can. 

> The only thing I can imagine is that a restart is required and I didn't do that? I also can't delete vods through the UI, but I guess that's a separate issue.

I'm fairly sure this works for me. Are you sure it's not just the selected video you can't delete? That is something I'm aware of but probably don't care enough to rush to fix just now.

**Comment by rationalcoder** [comment]
You're right. It's just the selected video.

**Comment by aza547** [comment]
Thanks for the report, fix coming in next release. I'll open another issue for the delete thing.
