### ISSUE TITLE
[Request] Add chat overlay

### ISSUE THREAD

**Issue by JH0Ni-github** [aza547/wow-recorder#46]
Add customizable chat overlay. Re-sizeable and moveable black box would be nice enough but custom picture files would be nice too. :)

**Comment by aza547** [comment]
This is probably a bit tricky and unlikely to happen in the near future, agree it would be a nice feature though.

**Comment by aza547** [comment]
Although - if you think you know how, PRs welcome!

**Comment by tdaugaard** [comment]
This should be _fairly_ easy in theory, but it won't be possible in this app due to us not exposing the composition of the "OBS scene" to the user with draggable and resizable scene items.

It'd be quite an undertaking to add this in the current state of the app.

**Comment by aza547** [comment]
I don't think we're ever going to do this i'm afraid.

**Comment by aza547** [comment]
Lots of people asking for this so re-opening.

**Comment by aza547** [comment]
![image](https://user-images.githubusercontent.com/32389325/235314108-596c5c08-3bc2-4130-9dd1-fe2adf2650ee.png)

Getting there... just need to plumb it up to the user to be configurable now.

**Comment by aza547** [comment]
![image](https://user-images.githubusercontent.com/32389325/235347175-52075652-e421-49f7-9182-ae5cece8efa4.png)

Coming in next release!

**Comment by aza547** [comment]
https://github.com/aza547/wow-recorder/pull/390

**Comment by aza547** [comment]
Didn't to custom pictures yet, we'll see how much people complain about that.
