### ISSUE TITLE
Program wont record anything, but the "testing" does its own record and saves it

### ISSUE THREAD

**Issue by xprepaidx** [aza547/wow-recorder#461]
No idea what the deal is. Looks like a decent program. Your "logs" that the program generates doesnt specify why it doesnt record anything.

Testing the recording by doing its own test saves its own test like normal.

Then when in-game it says it sees wow is on and its watching

never records anything. Even gave the folder its suppose to save recordings to, the "everyone" permission with Full Access.

Log needs to be updated to say why it wont record sessions. Currently its kinda pointless if it doesnt say that.

**Comment by xprepaidx** [comment]
Found out how to get it to record.

You really need more visible instructions that we **need** to have an addon to auto start the combat logger by doing /combatlog, or to have an addon that automatically does it. I only discovered i needed one by the "recommended combat logger addon" on your site that is subtly there. Didnt see anything like that in the wow recorder addon itself or the instructions here

**Comment by aza547** [comment]
I think it's totally standard behaviour that the "logs" don't log the absence of anything to record. 

Fair point regarding the description on the site being a bit misleading. I'll tweak the wording there. It's not "I recommend downloading a combat logging addon" but more "you must download a combat logging addon, here's the recommendation".
