### ISSUE TITLE
custom setting (pull timer) for starting of a recording

### ISSUE THREAD

**Issue by rml9ty** [aza547/wow-recorder#467]
I would like the ability to change how many seconds before a boss is pulled the recording starts. as a disc priest for instance I like to check the timing of my ramps which start sometimes up to 10 seconds before the boss is actually pulled... I would love an option like that <3

**Comment by aza547** [comment]
we can't avoid a restart either as there is no criteria to do so (no combat log event till the instant of the pull), although it's probably fine in 95% of boss pulls where the restart doesn't fall in the 10s leading to the pull, and so long as you pull within 5 mins of your previous wipe then it will always be fine

**Comment by aza547** [comment]
thought about this a bit more - afraid I won't do this given the complications mentioned above - sorry!

**Comment by rml9ty** [comment]
Too bad :( but if there isn't a way to circumvent the issues you mentioned then that's how it is. Thanks for considering it though!
