### ISSUE TITLE
[Request] Add config for audio and video input

### ISSUE THREAD

**Issue by JH0Ni-github** [aza547/wow-recorder#47]
Title.

**Comment by aza547** [comment]
Along with this it would be great to add a dropdown to select audio input device for mic.

**Comment by aza547** [comment]
Also this [reddit comment](https://www.reddit.com/r/worldofpvp/comments/wdrvys/warcraft_recorder_a_lightweight_nofuss/iktmed5/?context=3).

I think some better configuration and understanding of OBS will resolve this.

**Comment by ManagerWoW** [comment]
OBS 28 will be adding in support for capturing audio from specific applications, eliminating the need for virtual audio cables or the [win-capture-audio](https://obsproject.com/forum/resources/win-capture-audio.1338/) plugin. As of Aug 20, 28.0 beta is flagged as a release candidate and should be arriving in the next few weeks.

Feature PR: https://github.com/obsproject/obs-studio/pull/5218

**Comment by aza547** [comment]
https://github.com/aza547/wow-recorder/pull/89
