### ISSUE TITLE
aspect ratio changes makes the video a little weird.

### ISSUE THREAD

**Issue by justinabrahms** [aza547/wow-recorder#470]
**Describe the bug**

I have an 8k display (5120x2160). When the video is taken, it squashes it horizontally, which makes everything look a bit odd.

**To Reproduce**
Just play the game on a very wide screen. Resulting videos are squished.

**Expected behavior**
You know.. not squished video.

**Screenshots**
Full screen video after it was taken:
![image](https://github.com/aza547/wow-recorder/assets/3853/5e998972-b7d4-4386-bba8-6c52aee15a7b)

Where there are black bars on the side.. there should be video.

**Comment by aza547** [comment]
Can you share the WR log please?

**Comment by justinabrahms** [comment]
https://gist.github.com/justinabrahms/a84b9a355eab49578e515581db5ff1ad

**Comment by justinabrahms** [comment]
also worth noting (though perhaps in a second ticket) that the resulting video didn't appear to have sound.

**Comment by aza547** [comment]
I'm on mobile so hard to read the log, but looks like you maybe need to set your resolution and audio devices up in the scene tab? 

I'll look in more detail when I can get to a PC if that doesn't help.
