### ISSUE TITLE
Azure Vault timer wrong

### ISSUE THREAD

**Issue by JH0Ni-github** [aza547/wow-recorder#500]
I think you have missed some update to at least AV timer (there also was a recent hotfix to Uldaman timer). Just did a key finishing in 33:34 and it shows as depleted, although it was timed in game. The timer seems to be 37:30 per a WeakAura I'm using but maybe you can double check from somewhere.

**Comment by aza547** [comment]
Thanks - assume you are right. Had a quick google for some timers but didn't find anything. I'll try again when I get a chance.

**Comment by aza547** [comment]
Some data here: https://epiccarry.com/blogs/wow-mythic-season4-guide/ but matches what is already in the code so probs wrong.
