### ISSUE TITLE
Cursor Trapped when using Parsec

### ISSUE THREAD

**Issue by BrandonFreeck** [aza547/wow-recorder#503]
**Describe the bug**
When connecting to wow/playing via Parsec, when warcraft recorder is enabled and wow is booted, the mouse cursor is trapped in the parsec window as opposed to being able to freely leave it.

**To Reproduce**
Connect to a Desktop via Parsec
Observer mouse behavior allowing it to leave the parsec windown on the client machine/go to other non parsec windows
Start Warcraft Recorder
Start World of Warcraft
Observe mouse behavior, now trapped to the parsec screen
Quit Warcraft Recorder
Observe restored expected mouse behavior

**Comment by aza547** [comment]
have no means to reproduce this and never heard of parsec i'm afraid, happy to take a fix if you have one but not expecting to look into this so closing
