### ISSUE TITLE
Intel QuickSync support?

### ISSUE THREAD

**Issue by MediMilk** [aza547/wow-recorder#514]
Does WoW-Recorder support Intel QuickSync as an option for recording?

**Comment by aza547** [comment]
Not currently, although I got the feeling that it was probably possible. I have no means to test it though as I don't have the hardware. Happy to take a PR for it if you fancy implementing it.

**Comment by aza547** [comment]
Might just be a case of updating some enums allowing it to be selected if it's available.

**Comment by MediMilk** [comment]
I am terrible at programming, but I will give it a shot. Don't count on me though.

**Comment by aza547** [comment]
Some pointers... 

The app will currently log any available encoders but only prevent a subset of those in the UI that I have tested.

The logging (see Recorder.ts):
```
  /**
   * Return an array of all the encoders available to OBS.
   */
  public getAvailableEncoders() {
    console.info('[Recorder] Getting available encoders');

    if (!this.obsInitialized) {
      throw new Error('[Recorder] OBS not initialized');
    }

    const encoders = osn.VideoEncoderFactory.types();
    console.info('[Recorder]', encoders);

    return encoders;
  }
```

The filtering, see VideoBaseConbtrols.tsx:

```
useEffect(() => {
    const getAvailableEncoders = async () => {
      const allEncoders = await ipc.invoke('getEncoders', []);

      const availableEncoders = allEncoders
        .filter((s: string) => encoderFilter(s, highRes))
        .map(mapStringToEncoder)
        .sort((a: Encoder, b: Encoder) => a.type < b.type);

      setEncoders(availableEncoders);
    };
```

First step I'd suggest is check the logs on your PC if quick sync is logged as an available encoder.

**Comment by aza547** [comment]
Also see https://github.com/aza547/wow-recorder/issues/380

**Comment by aza547** [comment]
No action here so closing.
