### ISSUE TITLE
Name videos more sensibly

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#52]
Never worked out how to change the output file name in OSN / OBS. 

Would be good to for a bunch of reasons.

**Comment by tdaugaard** [comment]
Do we have to? Only the final cut video would be relevant to change the name of, and that's in `finalVideoPath` in `cutVideo()` in `util.ts` if I'm not mistaken.

**Comment by aza547** [comment]
I agree this is mostly uninteresting. I think we can just tell ffmpeg to spit out a file name of our choosing. Benefit of this is it looks better to users.

The reason it would be good to work out the OBS config such that the buffer recordings could be renamed is it would give us a mechanism to stop finding the video file by listing all MP4s in the .temp dir and then taking the newest. That feels a bit rubbish.

**Comment by tdaugaard** [comment]
Don't get me wrong, I am _hugely_ in favour of this! I have already planned the naming formats for M+ :p

> The reason it would be good to work out the OBS config such that the buffer recordings could be renamed is it would give us a mechanism to stop finding the video file by listing all MP4s in the .temp dir and then taking the newest. That feels a bit rubbish.

I get it - I actually don't dislike the current mechanism - it works reliably.
