### ISSUE TITLE
Add spacebar to start/stop video binds

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#537]
![{75D6CC98-FE10-4842-8B70-3635C7D4E211}](https://github.com/user-attachments/assets/5873d4d7-bf18-4af5-8166-53f0d72b6f60)

**Comment by vaisest** [comment]
I noticed from my media key issue that this is a very simple change:

```diff
--- a/src/renderer/VideoPlayer.tsx
+++ b/src/renderer/VideoPlayer.tsx
@@ -721,8 +721,9 @@ export const VideoPlayer = (props: IProps) => {
       return;
     }

-    if (e.key === 'k') {
+    if (e.key === 'k' || e.key === ' ') {
       togglePlaying();
+      e.preventDefault();
     }

     if (e.key === 'j' || e.key === 'ArrowLeft') {
```

Though it prevents space from scrolling down the list and working during when selecting buttons with tab. Is this the intention?

**Comment by aza547** [comment]
Thanks. I've grabbed this change. It was never intentional for space to have any effects otherwise so happy to lose those.
