### ISSUE TITLE
Software doesn't open and is only shown in the task manager

### ISSUE THREAD

**Issue by LethalJoke** [aza547/wow-recorder#552]
Randomly, when I try to launch the software it won't start
I can see it in the task manager but there's no windows or anything, it's not minimized in the system tray either
I've no idea how to get logs or anything to help you, the only way I've found to get it working is to reboot the computer

**Comment by aza547** [comment]
Afraid not much I can do with this without logs.  See the help channel in discord on how to get those. 

Feel free to open this when you provide them and I can take a look.
