### ISSUE TITLE
Don't require ownership of output directory

### ISSUE THREAD

**Issue by kshannoninnes** [aza547/wow-recorder#553]
**Is your feature request related to a problem? Please describe.**
I would love to use the app, but I prefer to store my recordings on my home server. However, this app seems to require ownership of the directory, which I do not want to give. Is there a reason it requires ownership instead of just appropriate write permissions?

**Describe the solution you'd like**
Allow valid config when directory permissions are acceptable

**Comment by aza547** [comment]
What error are you seeing? I'm not sure I've ever made an explicit check for this.

There is some code that checks the directory is empty, or contains a well formed set of WCR videos and nothing else; that's aimed to preventing people setting a folder of existing videos only to have WCR remove the ones it didn't make itself.

**Comment by aza547** [comment]
No reply so closing. Please feel free to reopen if you have further comments.
