### ISSUE TITLE
Warcraft Recorder makes out of focus windows framerate drops significantly

### ISSUE THREAD

**Issue by qstrql** [aza547/wow-recorder#565]
**Describe the bug**
If you run WoW and Warcraft recorder in the background, even outside of content that's supposed to be recorded (eg: questing or running in dornogal), the framerates of my other monitor drops significantly and most videos are unwatchable.

**To Reproduce**
1. Launch WoW and WoWRecorder on main monitor
2. Launch google and any youtube video on 2nd monitor
3. optional(Launch any program that allows you to see the framerate of your monitors)
4. Focus your window on WoW and see the framerate drop on other monitors

**Expected behavior**
No frame rate drop

**Additional context**
Closing WoW Recorder removes this problem entirely, so I'm pretty sure this is the culprit

**Comment by aza547** [comment]
WCR is always recording when WoW is open, that's just how it works (for good reasons). So the difference between "in or out of recordable content" isn't really meaningful.  

What drop are you seeing? Is it locking to say 60fps or is it just a performance drop? Are you using a hardware encoder or software encoder? The former is much more efficient and almost always performs better in terms of FPS. I'd advise checking your settings.

I suspect this is just "recording puts some load on your PC and you have to suck it up" I'm afraid. If you think there is still an issue here, feel free to reopen.

**Comment by qstrql** [comment]
Well it goes from 144fps locked to less than 15fps. I have a 13700k and 4070 ti super, so it's kinda odd the drop is that big. I'm using software encoder but i'll switch to hardware and see if it's better. Thanks for the fast answer !
