### ISSUE TITLE
Microphone streaming causes windows to not sleep/hibernate

### ISSUE THREAD

**Issue by barrj4** [aza547/wow-recorder#57]
Microphone recording stops windows from windows from sleeping on its own. From the terminal command "powercfg -requests" with the application in the task bar (WOW not running):

```
C:\WINDOWS\system32>powercfg -requests
DISPLAY:
None.

SYSTEM:
[DRIVER] Steam Streaming Microphone (ROOT\SteamStreamingMicrophone\0000)
An audio stream is currently in use.
[DRIVER] USB Audio 2.0 (USB\VID_30BE&PID_0101&MI_00\6&3c99bba&0&0000)
An audio stream is currently in use.
[DRIVER] USB Audio Device (USB\VID_0D8C&PID_9600&MI_00\6&2f66cdae&0&0000)
An audio stream is currently in use.
[DRIVER] Legacy Kernel Caller

AWAYMODE:
None.

EXECUTION:
None.

PERFBOOST:
None.

ACTIVELOCKSCREEN:
None.
```

After closing the wow-recorder app:

```
C:\WINDOWS\system32>powercfg -requests
DISPLAY:
None.

SYSTEM:
None.

AWAYMODE:
None.

EXECUTION:
None.

PERFBOOST:
None.

ACTIVELOCKSCREEN:
None.
```

**Comment by aza547** [comment]
Thanks for the report. Will look at fixing soon.

**Comment by tdaugaard** [comment]
I was doing a few tests on this yesterday and I think it stems from OBS recording in the background _before_ the actual recording of content is triggered. Is that a fair assumption?

I tried a simple commenting out of `setupSources()` first, and then `osn.Global.setOutputSource()` later and found the latter to fix the problem, but then obviously OBS won't record any sound at all ;)

**Comment by tdaugaard** [comment]
This can only realistically be fixed by _not_ recording sound (disabling the sound sources) while recording the buffer and only enabling the sound when we detect an event that starts the recording, but that obviously would mean we could lose up to like 30 seconds of audio in the beginning.

**Comment by barrj4** [comment]
Would it be possible to check if the game is running and if not just stop recording to the buffer? the game will also stop windows from sleeping.

**Comment by tdaugaard** [comment]
Yes, that would totally be possible and an easy fix.

**Comment by aza547** [comment]
> Would it be possible to check if the game is running and if not just stop recording to the buffer? the game will also stop windows from sleeping.

We already do this?

**Comment by tdaugaard** [comment]
> We already do this?

Yes, but the audio sources are still being kept open by OBS even if you stop buffer recording. Check out #204 for a possible fix to this.

**Comment by aza547** [comment]
I've backed this out as the fix was causing #220

**Comment by aza547** [comment]
A fix for this is finally coming in the next release.

**Comment by aza547** [comment]
Ugh, design changed a bit and makes this harder: https://obsproject.com/forum/threads/obs-prevents-screen-sleep-any-work-around.111687/.

Seems that if OBS is initialized we'll never be able to sleep. 

A good option seems to be shutdown OBS when WoW is closed - but that takes a few seconds of synchronous programming that isn't acceptable from a UX point of view.

I'm going to look at how I can use Node to do this in a separate thread. Seems gross, but the alternate is having the app lock up for 2-3s every time WoW opens/closes.

**Comment by aza547** [comment]
OK, back in business on this. 

I re-examined the fix @tdaugaard made and found the issue which was it was clearing the video source in addition to the audio sources. 

Fixed in the next release, so closing.
