### ISSUE TITLE
M+ and BGs are untested

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#6]
...and probably broken.

**Comment by alexanderkershaw** [comment]
Suspect they are broken because we won't watch the right events. Easiest fix is probably to go queue a BG etc and then read the combat log to see what the start/end events are then add them to the python code.

**Comment by alexanderkershaw** [comment]
Also will need to add images for bg maps / dungeons too for the GUI to look good.

**Comment by aza547** [comment]
For BGs looks like there is no useful events suprisingly:

```
ahk@DESKTOP-C6ME3UB:/mnt/d/World of Warcraft/_retail_/Logs$ grep -v "SPELL_"  /mnt/d/checkouts/wow-recorder/resources/example-logs/rbg.txt | grep -v "SWING_" | grep -v "RANGE_" | grep -v "UNIT_DIED" | grep -v
"EMOTE"
8/14 10:53:06.469  COMBAT_LOG_VERSION,19,ADVANCED_LOG_ENABLED,1,BUILD_VERSION,9.2.5,PROJECT_ID,1
8/14 10:53:06.469  ZONE_CHANGE,998,"Zereth Mortis",0
8/14 10:53:06.548  ZONE_CHANGE,998,"Temple of Kotmogu",0
8/14 10:55:12.558  MAP_CHANGE,417,"Temple of Kotmogu",2083.333008,1522.916992,1743.750000,904.166992
8/14 10:58:37.027  ZONE_CHANGE,2374,"Zereth Mortis",0
```

Will need to start recording on MAP_CHANGE and end on ZONE_CHANGE?

**Comment by aza547** [comment]
Looks like this is accurate:

```
30 | Alterac Valley
2107 | Arathi Basin
529 | Arathi Basin (Classic)
1681 | Arathi Basin (Winter)
2177 | Arathi Basin Comp Stomp
1105 | Deepwind Gorge
566 | Eye of the Storm
968 | Eye of the Storm (Rated)
628 | Isle of Conquest
1803 | Seething Shore
727 | Silvershard Mines
607 | Strand of the Ancients
998 | Temple of Kotmogu
761 | The Battle for Gilneas
726 | Twin Peaks
489 | Warsong Gulch
```

**Comment by aza547** [comment]
Added initial support for BGs today. No doubt a few bugs so leaving this open.

Known issues:
- Hard to decide who won or lost, need to have a think here.
- Some epic BGs not included? Need an exhaustive list - Ashran, Wintergrasp, possibly others missing

**Comment by aza547** [comment]
Also I've turned off the win/loss indicator for BGs. No idea how to make that work.

**Comment by aza547** [comment]
Going to open a separate issue for m+, BGs are working now.
