### ISSUE TITLE
Huge temp file

### ISSUE THREAD

**Issue by Maldark** [aza547/wow-recorder#66]
Hi,
When resuming my PC from standby today I got a warning that my C drive was running low on space and that I needed to fix it immediately. To my surprise there was a 66GB file in the %temp%/WarcraftRecorder folder.

I have set my Warcraft Recorder up to save on my D-drive with a 200 GB capacity limit as I have plenty of space there, but space is scarce on the C drive.

![image](https://user-images.githubusercontent.com/6592802/188268987-f66fa03a-ef9e-4e15-beb7-63a2ddf72796.png)

For context, prior to heading to sleep last night I did an Upper Karazhan that was not finished, and probably didn't get the correct termination event in the combatlog.

**Comment by aza547** [comment]
Hi and thanks for the report. Can you share logs please? See #help channel in discord for advice on how to find them. 

I think this is a side effect of M+ not being supported yet, but I didn't realise that raid boss encounters and M+ bosses both use the ENCOUNTER_START / ENCOUNTER_END events.

So I suspect what has happened here is that some combination of events has left the recording running for ages. Logs will confirm. That's certainly a bug.

Another thing the app should probably do is not just assume its OK to use a Temp directory on the C drive. It should be configurable in-case people such as yourself have limited C drive space.

**Comment by Maldark** [comment]
I have attached the requested logs.

Let me know if you need anything else, thanks.

[WarcraftRecorder-2022-09-02.log](https://github.com/aza547/wow-recorder/files/9483176/WarcraftRecorder-2022-09-02.log)
[2022-09-02 13-35-26.txt](https://github.com/aza547/wow-recorder/files/9483178/2022-09-02.13-35-26.txt)

**Comment by tdaugaard** [comment]
> Another thing the app should probably do is not just assume its OK to use a Temp directory on the C drive. It should be configurable in-case people such as yourself have limited C drive space.

It could use the same directory as `storageDir`, but like `'${storageDir}/.temp'` or something like that?

**Comment by aza547** [comment]
I think this is fixed on main and will be available in the next release.

**Comment by aza547** [comment]
Atleast the m+ thing is, still should make the temp locction configurable or a subdir in the storage dir as @tdaugaard suggested elsewhere

**Comment by aza547** [comment]
Can you attach recent logs so I can confirm it is the issue?

**Comment by Maldark** [comment]
> Can you attach recent logs so I can confirm it is the issue?

[WarcraftRecorder-2022-09-05.log](https://github.com/aza547/wow-recorder/files/9577881/WarcraftRecorder-2022-09-05.log)
[WarcraftRecorder-2022-09-07.log](https://github.com/aza547/wow-recorder/files/9577882/
[2022-09-07 06-04-51.txt](https://github.com/aza547/wow-recorder/files/9577884/2022-09-07.06-04-51.txt)
[2022-09-07 09-22-53.txt](https://github.com/aza547/wow-recorder/files/9577885/2022-09-07.09-22-53.txt)
WarcraftRecorder-2022-09-07.log)

Logs attached as requested, let me know if you need anything else.

**Comment by tdaugaard** [comment]
@aza547 I will make a "_Temp storage dir_" setting later tonight - seems like a good idea.

**Comment by Maldark** [comment]
I think making a .temp dir would be ideal as we've already "assigned" space for the application there. Or at least make it default to that. 

And perhaps cap the size of the temp files... Maybe it isn't an issue on master now, but I've been deleting 80gb files left and right for the last few weeks.

**Comment by aza547** [comment]
See https://github.com/aza547/wow-recorder/commit/44c2655d35bece484ce87799fd6e381d7331c0b7. Hopefully much better in next release.
