### ISSUE TITLE
[Code style] eslint issues

### ISSUE THREAD

**Issue by tdaugaard** [aza547/wow-recorder#68]
I don't know if it's a case of not having defined too many rules for eslint, but there's a ton of formatting errors when source files are opened in VSCode with ESLint extension installed. Simple things like trailing white-space as well as missing semi-colons, commas, and what have we.

Would you be open to a PR with _only_ formatting related changes and if so, can we consider the current `.eslintrc.js` settings to be authoritative on the style (including 2 space indent, although most of the code is using 4)?

Thanks for your consideration.

**Comment by aza547** [comment]
Hi - yes certainly open to that. Symptom of this project being my first TS/JS project.

**Comment by aza547** [comment]
I do have the ESLint extension installed, I don't see the errors oddly. Interested in why not also!

**Comment by tdaugaard** [comment]
Here's an example:

![image](https://user-images.githubusercontent.com/875107/188280737-4c4a4b19-44cf-439c-9feb-cc05f64b79f8.png)

I'm not at all great at TS (but decent with JS and have a few decades of programming experience in general), but I read the code just fine.

I'll do a reformat of the code and make a PR and whatever you don't like, I'll fix it and update `.eslintrc` accordingly so it doesn't complain. Does that sound good to you?

**Comment by aza547** [comment]
Sounds awesome! Thanks!

**Comment by tdaugaard** [comment]
I noticed it was due to the Prettier extension, not ESLint. Without Prettier, there are no style errors, so I just disabled it :p

**Comment by tdaugaard** [comment]
Closing issue as it seeme ESLint/prettier was the problem as a combination.
