### ISSUE TITLE
Add a version check

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#74]
Something we discussed, a link back to GitHub to check for new versions and display if an upgrade is available would be nice.

Crucially it shouldn't be obnoxious, and should be easily dismissed if a user doesn't want to upgrade.

**Comment by aza547** [comment]
While in the area it would also be good to log the version, we don't do that currently.

**Comment by tdaugaard** [comment]
Perhaps take a look electron-builder https://www.electron.build/, which has an Auto Update feature if that's something you're interested in.

**Comment by aza547** [comment]
being handled here https://github.com/aza547/wow-recorder/pull/102

**Comment by aza547** [comment]
Actually that's just the adding of a version number to logs / title. We still want a check to confirm it's the latest.
