### ISSUE TITLE
Don't save raid encounter resets.

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#76]
Or atleast make it a configurable option to skip recording fights that are only a few seconds long?

Might affect legacy content runs but surely that's fine

**Comment by tdaugaard** [comment]
Any idea of how to abandon a recording that has been started, that we don't want to keep - it should be easy to have a setting like "_Discard recordings of encounters shorter han X seconds_", but the actual logic behind having the recorder discard what has already been recorded, I am unsure of that.

**Comment by aza547** [comment]
I think the logic is to put in a stop recording function that never calls finalizeVideo() - the finalizeVidoeo() function is responsible for cutting the temp recording to size and moving it to the storage dir. If we skip that and just restarted the buffering i think that's all we need.
