### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#85]
![image](https://user-images.githubusercontent.com/32389325/188959006-bd1c2ec1-812d-470b-ae3e-81afc5ea0e05.png)

![image](https://user-images.githubusercontent.com/32389325/188959051-a327505f-2939-4d35-b32b-eb2496be873d.png)

[WarcraftRecorder-2022-09-05.log](https://github.com/aza547/wow-recorder/files/9508984/WarcraftRecorder-2022-09-05.log)
[WarcraftRecorder-2022-09-06.log](https://github.com/aza547/wow-recorder/files/9508985/WarcraftRecorder-2022-09-06.log)

**Comment by tdaugaard** [comment]
Still relevant? I haven't seen anything like it and I've had it run for hours while gaming.

**Comment by aza547** [comment]
Pretty sure this wasn't a memory leak and was a problem with the users windows not closing wow processes.
