### ISSUE TITLE
Bad UX with "save" button

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#97]
> 1. What is happening?  On occasion (not every time), checking/unchecking the "save" property on a video will not actually check/uncheck.  Checking/unchecking also causes the app to freeze for about 5-10 seconds causing mouseclicks to become unresponsive in changing to new videos or pausing/unpausing.
> 2. What are you expecting to happen?  The "save" property to toggle when checked/unchecked and less lag between checking/unchecking and being able to continue using the app.
> 3. What icon is showing in the bottom left of the application?  I did all this with WoW closed so a snoozing person icon.
> 4. What version are you running? 2.6.0

Reported by tekrul on discord.

**Comment by tdaugaard** [comment]
Could this be related to the memory leak issues caused by the EventEmitters that was fixed recently?

**Comment by aza547** [comment]
> Could this be related to the memory leak issues caused by the EventEmitters that was fixed recently?

Doesn't seem impossible, we could have asked him to restart the app and retry, but I think it might just be a slow HDD as discussed in discord.

![image](https://user-images.githubusercontent.com/32389325/190088605-27763d64-147d-42e4-876a-b031823d3151.png)

**Comment by aza547** [comment]
I think this works fine in the new UI. Not convinced it's bad enough to do something with.
