### ISSUE TITLE
remember muted state

### ISSUE THREAD

**Issue by rml9ty** [aza547/wow-recorder#99]
by switching between videos the muted state is reset to unmuted. I'd love it to remember the setting.
also: really, really great work! keep it up

**Comment by tdaugaard** [comment]
This is a feature I've wanted too!

**Comment by aza547** [comment]
We do seem to still lose muted state when a new video is recorded, but retain it over changing video, so this is improved but not entirely fixed I think.

**Comment by aza547** [comment]
(on main, nothing is actually released yet)

**Comment by aza547** [comment]
Also when changing categories

**Comment by tdaugaard** [comment]
> Also when changing categories - it seems there is a volume state PER category instead of a global one

That might be true. I'm thinking I could make some video settings globally for the whole app, and then create an IPC channel `get/setVideoPlayerSettings` that could be used to .. well .. get and set video player settings. :p
